// File: /home/mjh/front/apps/web/app/(ai)/ai-apps/prompt-lessons/app.tsx
"use client"

import { useState, useEffect } from "react"
import { BookOpen, GraduationCap, RotateCcw } from "lucide-react"
import { Button } from "@workspace/ui/components/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@workspace/ui/components/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@workspace/ui/components/tabs"
import { motion } from "framer-motion"
import { PreflightError } from "@/app/(ai)/components/preflight-error"
import { getErrorDisplay } from "@/app/(ai)/lib/preflight-checks/error-handler"
import { container, item } from "@/lib/animation"
import { APP_CONFIG } from "./config"
import { lessons, getAllLessons, getLessonById, getStaticLessonContent } from "./lessons/lesson-data"
import { Lesson, LessonContent } from "./schema"
import LessonBrowser from "./components/lesson-browser"
import LessonContentView from "./components/lesson-content"

export default function PromptLessonsTool() {
    const [activeTab, setActiveTab] = useState("browse")
    const [selectedLesson, setSelectedLesson] = useState<Lesson | null>(null)
    const [lessonContent, setLessonContent] = useState<LessonContent | null>(null)
    const [error, setError] = useState<any>(null)
    const [isLoading, setIsLoading] = useState(false)
    const [currentLessons, setCurrentLessons] = useState<Lesson[]>([])
    const [activeFilter, setActiveFilter] = useState<string>("all")

    // Initialize lessons
    useEffect(() => {
        setCurrentLessons(getAllLessons())
    }, [])

    // Function to handle lesson selection and fetch lesson content
    const handleSelectLesson = async (lesson: Lesson) => {
        try {
            setSelectedLesson(lesson)
            setLessonContent(null)
            setError(null)
            setIsLoading(true)
            setActiveTab("lesson")

            console.log("Fetching lesson content for:", lesson.id)

            // For now, we'll just simulate a response with different
            // content based on the lesson ID
            // Replace the setTimeout block with this code (around line 45)
            setTimeout(() => {
                setIsLoading(false)

                // Check if this is a static lesson with predefined content
                if (lesson.contentType === 'static') {
                    const staticContent = getStaticLessonContent(lesson.id);

                    // If static content exists, use it
                    if (staticContent) {
                        setLessonContent(staticContent);
                        return;
                    }
                }

                // If we're here, either:
                // 1. This is an AI-generated lesson
                // 2. This is a static lesson but content wasn't found (fallback)

                // In a production implementation, this would make an API call to 
                // generate or retrieve the lesson content

                // For now, provide a generic placeholder for AI-generated lessons
                setLessonContent({
                    introduction: `This is a placeholder introduction for the ${lesson.title} lesson. In a complete implementation, this content would be ${lesson.contentType === 'ai-generated' ? 'generated by AI' : 'stored statically'}.`,
                    examples: [
                        {
                            good: "Write a detailed analysis of climate change impacts on coastal cities, including statistical trends from the last decade and projected future scenarios.",
                            bad: "Tell me about climate change and cities.",
                            explanation: "The improved prompt specifies the exact subject (coastal cities), the type of content wanted (detailed analysis), and includes specific elements to include (statistical trends, projections)."
                        }
                    ],
                    exercises: [
                        {
                            id: `ex1-${lesson.id}`,
                            type: "improve",
                            title: "Improve clarity",
                            instructions: "Rewrite this vague prompt to make it more specific and clear.",
                            prompt: "Give me information about technology."
                        },
                        {
                            id: `ex2-${lesson.id}`,
                            type: "true-false",
                            title: "Test Your Knowledge",
                            instructions: "Determine whether this statement about prompt engineering is true or false.",
                            statement: "Adding more words to a prompt always makes it more effective.",
                            isTrue: false
                        }
                    ],
                    conclusion: `This concludes our lesson on ${lesson.title}. You've learned the key principles and practiced applying them. Continue to the next lesson to build on these skills.`
                });
            }, 1500)

        } catch (err: any) {
            console.error("Failed to load lesson:", err)
            setError({
                code: 'api_error',
                message: err.message || 'An error occurred while loading the lesson',
                severity: 'error'
            })
            setIsLoading(false)
        }
    }

    // Function to filter lessons
    const filterLessons = (filterType: string, value: string) => {
        setActiveFilter(`${filterType}-${value}`)

        if (filterType === 'difficulty') {
            setCurrentLessons(lessons.filter(lesson => lesson.difficulty === value))
        } else if (filterType === 'category') {
            setCurrentLessons(lessons.filter(lesson => lesson.category === value))
        } else {
            setCurrentLessons(getAllLessons())
        }
    }

    // Function to handle going back to the browse view
    const handleBack = () => {
        setActiveTab("browse")
        setSelectedLesson(null)
        setLessonContent(null)
    }

    const errorConfig = error ? getErrorDisplay({
        passed: false,
        code: error.code,
        message: error.message,
        severity: error.severity,
        details: error.details
    }) : null

    return (
        <motion.div
            variants={container}
            initial="hidden"
            animate="visible"
            className="space-y-8"
        >
            <motion.div variants={item} className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tight">{APP_CONFIG.name}</h1>
                <p className="text-muted-foreground">
                    {APP_CONFIG.description}
                </p>
            </motion.div>

            <motion.div variants={item}>
                <Card className="overflow-hidden">
                    <CardHeader>
                        <CardTitle className="flex items-center">
                            <GraduationCap className="mr-2 h-5 w-5 text-primary" />
                            Learn Prompt Engineering
                        </CardTitle>
                        <CardDescription>
                            Interactive lessons to help you master the art of crafting effective prompts.
                        </CardDescription>
                    </CardHeader>

                    <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
                        <div className="px-6">
                            <TabsList className="grid w-full grid-cols-2">
                                <TabsTrigger value="browse" onClick={handleBack}>Browse Lessons</TabsTrigger>
                                <TabsTrigger value="lesson" disabled={!selectedLesson}>Active Lesson</TabsTrigger>
                            </TabsList>
                        </div>

                        <TabsContent value="browse" className="m-0">
                            <CardContent className="p-6">
                                {errorConfig && <PreflightError config={errorConfig} />}

                                <LessonBrowser
                                    lessons={currentLessons}
                                    activeFilter={activeFilter}
                                    onFilterChange={filterLessons}
                                    onSelectLesson={handleSelectLesson}
                                />
                            </CardContent>
                        </TabsContent>

                        <TabsContent value="lesson" className="m-0">
                            <CardContent className="p-6">
                                {errorConfig && <PreflightError config={errorConfig} />}

                                {selectedLesson && lessonContent ? (
                                    <LessonContentView
                                        lesson={selectedLesson}
                                        content={lessonContent}
                                        isLoading={isLoading}
                                    />
                                ) : !isLoading ? (
                                    <div className="text-center text-muted-foreground py-8">
                                        <p>Select a lesson to get started</p>
                                    </div>
                                ) : null}
                            </CardContent>
                        </TabsContent>
                    </Tabs>

                    <CardFooter className="flex justify-between p-6 border-t">
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={handleBack}
                            disabled={activeTab === 'browse'}
                        >
                            <RotateCcw className="mr-2 h-4 w-4" />
                            Back to Lessons
                        </Button>
                    </CardFooter>
                </Card>
            </motion.div>
        </motion.div>
    )
}